### ISSUE TITLE
Failed to append initial transactions: Duplicate output public key

### ISSUE THREAD

**Issue by ItzBubschki** [mobilecoinofficial/desktop-wallet#333]
OS: Ubuntu 22.04
Wallet 1.4.1 and 1.9.1

When trying to unluck my wallet i get a Network error.
According to full-service...log it threw the following error for version 1.4.1:

```
OH NO, WE CRASHED :( thread main on ./full-service
Details: panicked at 'Failed to appened initial transactions: DuplicateOutputPublicKey', full-service/src/config.rs:302:22
   0:     0x55c545150211 - backtrace::backtrace::libunwind::trace::ha022bc077a162e1b
...
```

And pretty much the same error but with less info in version 1.9.1:
```
OH NO, WE CRASHED :( thread main on ./full-service
Details: panicked at /__w/full-service/full-service/full-service/src/config.rs:366:26:
Failed to append initial transactions: Duplicate output public key
```

**Comment by eranrund** [comment]
I think deleting and having full-service re-download the ledger database would fix that for you.
I think that on Linux machines it's inside `~/.config/MobileCoin\ Wallet/full-service/ledger-db`. 
Note that the ledger-db is separate from the wallet-db where your keys are stored, so this should be a safe operation - but maybe just in case, move it somewhere else instead of deleting until you see it solved your issue.

**Comment by ItzBubschki** [comment]
thanks!
